version: "3.9"
services:
    nginx:
        image: nginx:1.20.2-alpine
        container_name: clean-nginx
        ports:
            - 8081:80
        volumes:
            - ./src:/home/clean/src
            - ./docker-compose/nginx/conf:/etc/nginx/conf.d/
            - ./docker-compose/logs/nginx:/home/clean/logs

    php:
        build: ./docker-compose/php/
        container_name: clean-php
        working_dir: /home/clean/src
        volumes: 
            - ./src:/home/clean/src
            - ./docker-compose/logs/php-fpm:/var/log/php-fpm
        env_file:
            - ./docker-compose/mysql/.env
    
    db-mariadb:
        container_name: clean-db-mariadb
        image: mariadb:10.6.5
        env_file:
            - ./docker-compose/mysql/.env
        volumes:
            - ./docker-compose/mysql/data/mariadb:/var/lib/mysql
        ports:
            - 3306:3306